runtime: php55

handlers:
  - url: /([^/]+)$
    static_files: \1.html
    upload: (.*).html
    mime_type: text/html
  - url: /([^/]+)/(v\d+)$
    static_files: \1-\2.html
    upload: (.*).html
    mime_type: text/html
